# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.
# login
login:
    path: /login
    defaults: { _controller: 'App\Controller\SecurityController::loginAction' }

logout:
    path: /logout
    defaults: { _controller: 'App\Controller\SecurityController::logoutAction' }

home:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::homeAction' }

# client

client:
    path: /panel/index
    defaults: { _controller: 'App\Controller\ClientController::indexAction' }

searchClient:
    path: /panel/search
    defaults: { _controller: 'App\Controller\ClientController::searchAction' }

createclient:
    path: /panel/create
    defaults: { _controller: 'App\Controller\ClientController::createAction' }

editclient:
    path: /panel/edit/{id}
    defaults: { _controller: 'App\Controller\ClientController::editAction' }

saveclient:
    path: /panel/save
    defaults: { _controller: 'App\Controller\ClientController::saveAction' }

deletedclient:
    path: /panel/deleted
    defaults: { _controller: 'App\Controller\ClientController::deletedAction' }

showclient:
    path: /panel/show/{id}
    defaults: { _controller: 'App\Controller\ClientController::showAction' }