# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.
# login
login:
    path: /login
    defaults: { _controller: 'App\Controller\SecurityController::loginAction' }
    methods: [GET, POST]

logout:
    path: /logout
    defaults: { _controller: 'App\Controller\SecurityController::logoutAction' }

home:
    path: /panel
    defaults: { _controller: 'App\Controller\DefaultController::homeAction' }
    methods: GET

# client

client:
    path: /panel/index
    defaults: { _controller: 'App\Controller\ClientController::indexAction' }
    methods: GET

searchClient:
    path: /panel/search
    defaults: { _controller: 'App\Controller\ClientController::searchAction' }
    methods: POST

createclient:
    path: /panel/create
    defaults: { _controller: 'App\Controller\ClientController::createAction' }
    methods: GET

editclient:
    path: /panel/edit/{id}
    defaults: { _controller: 'App\Controller\ClientController::editAction' }
    methods: GET

saveclient:
    path: /panel/save
    defaults: { _controller: 'App\Controller\ClientController::saveAction' }
    methods: POST

deletedclient:
    path: /panel/deleted
    defaults: { _controller: 'App\Controller\ClientController::deletedAction' }
    methods: POST

showclient:
    path: /panel/show/{id}
    defaults: { _controller: 'App\Controller\ClientController::showAction' }
    methods: GET