# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.
# login
login:
    path: /login
    defaults: { _controller: 'App\Controller\SecurityController::loginAction' }

logout:
    path: /logout
    defaults: { _controller: 'App\Controller\SecurityController::logoutAction' }

home:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::homeAction' }

# client

client:
    path: /index
    defaults: { _controller: 'App\Controller\ClientController::indexAction' }

createclient:
    path: /create
    defaults: { _controller: 'App\Controller\ClientController::createAction' }

editclient:
    path: /edit/{id}
    defaults: { _controller: 'App\Controller\ClientController::editAction' }

saveclient:
    path: /save
    defaults: { _controller: 'App\Controller\ClientController::saveAction' }

deletedclient:
    path: /deleted
    defaults: { _controller: 'App\Controller\ClientController::deletedAction' }

showclient:
    path: /show/{id}
    defaults: { _controller: 'App\Controller\ClientController::showAction' }